//HintName: Sample_Order_ParchmentModel.g.cs
// <auto-generated />
#nullable enable

using System.Collections.Generic;
namespace Sample;
partial class Order
{
  public static string TemplatePath => "template.docx";
  public static string TemplateName => "Order";

  static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Order =
  {
    new("Items", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Order)o).Items)),
  };
  static readonly global::Parchment.Generated.StringListMapEntry[] _StringLists =
  {
    new("Items", o => ((global::Sample.Order)o).Items),
  };

  public static void RegisterWith(global::Parchment.TemplateStore store, string? basePath = null)
  {
    global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Order), _Accessors_global__Sample_Order);
    global::Parchment.Generated.GeneratedRegistration.RegisterStringList(typeof(global::Sample.Order), _StringLists);
    var path = basePath is null ? TemplatePath : global::System.IO.Path.Combine(basePath, TemplatePath);
    store.RegisterDocxTemplate<global::Sample.Order>(TemplateName, path);
  }
}
