//HintName: Sample_Order_ParchmentModel.g.cs
// <auto-generated />
#nullable enable

using System.Collections.Generic;
namespace Sample;
partial class Order
{
  public static string TemplatePath => "template.docx";
  public static string TemplateName => "Order";

  static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Order =
  {
    new("Number", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Order)o).Number)),
    new("PurchaseOrder", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Order)o).PurchaseOrder)),
    new("Approved", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Order)o).Approved)),
    new("Delivery", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Order)o).Delivery)),
    new("SignedAt", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Order)o).SignedAt)),
    new("PickupTime", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Order)o).PickupTime)),
    new("Status", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Order)o).Status)),
    new("Discount", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Order)o).Discount)),
    new("Instructions", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Order)o).Instructions)),
    new("Customer", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Order)o).Customer)),
  };
  static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Status =
  {
    new("Draft", new global::Fluid.Accessors.DelegateAccessor((_, _) => global::Sample.Status.Draft)),
    new("Final", new global::Fluid.Accessors.DelegateAccessor((_, _) => global::Sample.Status.Final)),
  };
  static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Customer =
  {
    new("Email", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Customer)o).Email)),
  };
  static readonly global::Parchment.Generated.EditableFieldMapEntry[] _Editables =
  {
    new("PurchaseOrder", global::Parchment.Generated.EditableFieldKind.Text, typeof(string), false, o => ((global::Sample.Order)o).PurchaseOrder, (o, v) => { ((global::Sample.Order)o).PurchaseOrder = (string)v!; }, static o => true, false, null),
    new("Approved", global::Parchment.Generated.EditableFieldKind.Checkbox, typeof(bool), false, o => ((global::Sample.Order)o).Approved, (o, v) => { ((global::Sample.Order)o).Approved = (bool)v!; }, static o => true, false, null),
    new("Delivery", global::Parchment.Generated.EditableFieldKind.Date, typeof(global::System.DateTime), false, o => ((global::Sample.Order)o).Delivery, (o, v) => { ((global::Sample.Order)o).Delivery = (global::System.DateTime)v!; }, static o => true, false, "dd MMM yyyy"),
    new("SignedAt", global::Parchment.Generated.EditableFieldKind.DateTimeOffset, typeof(global::System.DateTimeOffset), false, o => ((global::Sample.Order)o).SignedAt, (o, v) => { ((global::Sample.Order)o).SignedAt = (global::System.DateTimeOffset)v!; }, static o => true, false, null),
    new("PickupTime", global::Parchment.Generated.EditableFieldKind.Time, typeof(global::System.TimeOnly), false, o => ((global::Sample.Order)o).PickupTime, (o, v) => { ((global::Sample.Order)o).PickupTime = (global::System.TimeOnly)v!; }, static o => true, false, null),
    new("Status", global::Parchment.Generated.EditableFieldKind.DropDown, typeof(global::Sample.Status), false, o => ((global::Sample.Order)o).Status, (o, v) => { ((global::Sample.Order)o).Status = (global::Sample.Status)v!; }, static o => true, false, null),
    new("Discount", global::Parchment.Generated.EditableFieldKind.Number, typeof(decimal), true, o => ((global::Sample.Order)o).Discount, (o, v) => { ((global::Sample.Order)o).Discount = (decimal?)v; }, static o => true, false, null),
    new("Instructions", global::Parchment.Generated.EditableFieldKind.Text, typeof(string), false, o => ((global::Sample.Order)o).Instructions, (o, v) => { ((global::Sample.Order)o).Instructions = (string)v!; }, static o => true, true, null),
    new("Customer.Email", global::Parchment.Generated.EditableFieldKind.Text, typeof(string), true, o => ((global::Sample.Order)o).Customer?.Email, (o, v) => { var p = ((global::Sample.Order)o).Customer; if (p != null) { p.Email = (string?)v; } }, o => ((global::Sample.Order)o).Customer != null, false, null),
  };

  public static void RegisterWith(global::Parchment.TemplateStore store, string? basePath = null)
  {
    global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Order), _Accessors_global__Sample_Order);
    global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Status), _Accessors_global__Sample_Status);
    global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Customer), _Accessors_global__Sample_Customer);
    global::Parchment.Generated.GeneratedRegistration.RegisterEditable(typeof(global::Sample.Order), _Editables);
    var path = basePath is null ? TemplatePath : global::System.IO.Path.Combine(basePath, TemplatePath);
    store.RegisterDocxTemplate<global::Sample.Order>(TemplateName, path);
  }
}
