//HintName: Report_ParchmentModel.g.cs
// <auto-generated />
#nullable enable

using System.Collections.Generic;
partial class Report
{
  public static string TemplatePath => "template.md";
  public static string TemplateName => "Report";

  static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Report =
  {
    new("Name", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Report)o).Name)),
  };

  public static void RegisterWith(global::Parchment.TemplateStore store, string? basePath = null, global::System.IO.Stream? styleSource = null)
  {
    global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Report), _Accessors_global__Report);
    using var template = typeof(global::Report).Assembly.GetManifestResourceStream("MyProject.template.md") ??
              throw new global::System.InvalidOperationException("Template resource 'MyProject.template.md' was not found in the assembly.");
    using var reader = new global::System.IO.StreamReader(template);
    store.RegisterMarkdownTemplate<global::Report>(TemplateName, reader.ReadToEnd(), styleSource);
  }
}
