//HintName: Invoice_ParchmentModel.g.cs
// <auto-generated />
#nullable enable

using System.Collections.Generic;
partial class Invoice
{
  public static string TemplatePath => "template.docx";
  public static string TemplateName => "Invoice";

  static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Invoice =
  {
    new("Number", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Invoice)o).Number)),
  };

  public static void RegisterWith(global::Parchment.TemplateStore store, string? basePath = null)
  {
    global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Invoice), _Accessors_global__Invoice);
    using var template = typeof(global::Invoice).Assembly.GetManifestResourceStream("MyProject.template.docx") ??
              throw new global::System.InvalidOperationException("Template resource 'MyProject.template.docx' was not found in the assembly.");
    store.RegisterDocxTemplate<global::Invoice>(TemplateName, template);
  }
}
