//HintName: Sample_Empty_ParchmentModel.g.cs
// <auto-generated />
#nullable enable

using System.Collections.Generic;
namespace Sample;
partial class Empty
{
  [global::System.Runtime.CompilerServices.ModuleInitializer]
  internal static void InitializeParchmentTemplate()
  {
    global::Parchment.Generated.GeneratedRegistration.RegisterDocxTemplate(
      typeof(global::Sample.Empty),
      global::System.Convert.FromBase64String("scrubbed"));
  }
}
