//HintName: Sample_Invoice_ParchmentModel.g.cs
// <auto-generated />
#nullable enable

using System.Collections.Generic;
namespace Sample;
partial class Invoice
{
  static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Invoice =
  {
    new("Lines", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Invoice)o).Lines)),
  };
  static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Line =
  {
    new("Description", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Line)o).Description)),
  };

  [global::System.Runtime.CompilerServices.ModuleInitializer]
  internal static void InitializeParchmentTemplate()
  {
    global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Invoice), _Accessors_global__Sample_Invoice);
    global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Line), _Accessors_global__Sample_Line);
    global::Parchment.Generated.GeneratedRegistration.RegisterMarkdownTemplate(
      typeof(global::Sample.Invoice),
      "{% for line in Lines %}\n- {{ line.Description }}\n{% endfor %}");
  }
}
