//HintName: Sample_Outer_LetterModel_ParchmentModel.g.cs
// <auto-generated />
#nullable enable

using System.Collections.Generic;
namespace Sample;
partial class Outer
{
  partial class LetterModel
  {
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static class ParchmentGeneratedLetterModel
    {
      static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Outer_LetterModel =
      {
        new("Customer", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Outer.LetterModel)o).Customer)),
      };
      static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Customer =
      {
        new("Name", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Customer)o).Name)),
      };

      [global::System.Runtime.CompilerServices.ModuleInitializer]
      internal static void InitializeParchmentTemplate()
      {
        global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Outer.LetterModel), _Accessors_global__Sample_Outer_LetterModel);
        global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Customer), _Accessors_global__Sample_Customer);
        global::Parchment.Generated.GeneratedRegistration.RegisterDocxTemplate(
          typeof(global::Sample.Outer.LetterModel),
          global::System.Convert.FromBase64String("scrubbed"));
      }
    }
  }
}
