//HintName: Sample_Invoice_ParchmentModel.g.cs
// <auto-generated />
#nullable enable

using System.Collections.Generic;
namespace Sample;
partial class Invoice
{
  [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
  internal static class ParchmentGeneratedInvoice
  {
    static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Invoice =
    {
      new("Lines", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Invoice)o).Lines)),
    };
    static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Line =
    {
      new("Description", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Line)o).Description)),
    };
    static readonly global::Parchment.Generated.ExcelsiorTableMapEntry[] _ExcelsiorTables =
    {
      new("Lines", typeof(global::Sample.Line), o => ((global::Sample.Invoice)o).Lines, null, null, null, b => global::Sample.Invoice.ConfigureLines((global::Excelsior.WordTableBuilder<global::Sample.Line>)b)),
    };

    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void InitializeParchmentTemplate()
    {
      global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Invoice), _Accessors_global__Sample_Invoice);
      global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Line), _Accessors_global__Sample_Line);
      global::Parchment.Generated.GeneratedRegistration.RegisterExcelsiorTable(typeof(global::Sample.Invoice), _ExcelsiorTables);
      global::Parchment.Generated.GeneratedRegistration.RegisterDocxTemplate(
        typeof(global::Sample.Invoice),
        global::System.Convert.FromBase64String("scrubbed"));
    }
  }
}
